scripts:
  # "Pre" scripts run immediately after repos have been imported.
  pre:
    # Automatically runs script files within "scripts/pre/".
    - autorun.sh

  # "Post" scripts run at the end of the build process.
  post:
    # Automatically runs script files within "scripts/post/".
    - autorun.sh

# Custom RPM configuration.
rpm:
  # A list of urls of repositories that should be added to your system.
  # Tip: Use `%FEDORA_VERSION%` instead of static Fedora version numbers.
  repos:

  # These RPMs will be installed from your enabled repositories.
  install:
    # GNOME's GTK4 theme, many native apps and binaries require it.        
    - libadwaita
    # Needed for yafti (the first boot installer).
    - python3-pip

  # These RPMs will be removed from the system image.
  remove:
    # Remove the native firefox (from Fedora) in favor of the Flatpak.
    - firefox
    - firefox-langpacks
