scripts:
  # "Pre" scripts run immediately after repos have been imported.
  pre:
    # Automatically runs script files within "scripts/pre/".
    - autorun.sh

  # "Post" scripts run at the end of the build process.
  post:
    # Automatically runs script files within "scripts/post/".
    - autorun.sh

# Custom RPM configuration.
rpm:
  # A list of urls of repositories that should be added to your system.
  # Tip: Use `%FEDORA_VERSION%` instead of static Fedora version numbers.
  repos:
    - https://terra.fyralabs.com/terra.repo

  # These RPMs will be installed from your enabled repositories.
  install:
    - contractor

    - elementary-calculator
    - elementary-calendar
    - elementary-camera
    - elementary-capnet-assist
    - elementary-code
    - elementary-files
    - elementary-greeter
    - elementary-icon-theme
    - elementary-music
    - elementary-notifications
    - elementary-photos
    - elementary-print
    - elementary-screenshot-tool
    - elementary-shortcut-overlay
    - elementary-sideload
    - elementary-sound-theme
    - elementary-terminal
    - elementary-theme
    - elementary-videos
    - elementary-wallpapers

    - gala

    - gnome-session

    # GNOME's GTK4 theme, many native apps and binaries require it.
    - libadwaita

    - pantheon-agent-geoclue2
    - pantheon-agent-polkit
    - pantheon-session-settings
    - pantheon-tweaks

    - plank

    # Needed for yafti (the first boot installer).
    - python3-pip

    - switchboard
    - switchboard-plug-a11y
    - switchboard-plug-about
    - switchboard-plug-applications
    - switchboard-plug-bluetooth
    - switchboard-plug-display
    - switchboard-plug-keyboard
    - switchboard-plug-mouse-touchpad
    - switchboard-plug-networking
    - switchboard-plug-notifications
    - switchboard-plug-pantheon-shell
    - switchboard-plug-printers
    - switchboard-plug-sharing
    - switchboard-plug-sound

    - touchegg

    - wingpanel
    - wingpanel-applications-menu
    - wingpanel-indicator-bluetooth
    - wingpanel-indicator-datetime
    - wingpanel-indicator-keyboard
    - wingpanel-indicator-network
    - wingpanel-indicator-nightlight
    - wingpanel-indicator-notifications
    - wingpanel-indicator-power
    - wingpanel-indicator-session
    - wingpanel-indicator-sound

  # These RPMs will be removed from the system image.
  remove:
    # Remove the native Firefox.
    - firefox
    - firefox-langpacks
