scripts:
  # "Pre" scripts run immediately after repos have been imported.
  pre:
    # Automatically runs script files within "dx/scripts/pre/".
    - autorun.sh

  # "Post" scripts run at the end of the build process.
  post:
    # Automatically runs script files within "dx/scripts/post/".
    - autorun.sh

# Custom RPM configuration.
rpm:
  # A list of urls of repositories that should be added to your system.
  # Tip: Use `%FEDORA_VERSION%` instead of static Fedora version numbers.
  repos:
    - https://copr.fedorainfracloud.org/coprs/eyecantcu/android-udev-rules/repo/fedora-%FEDORA_VERSION%/eyecantcu-android-udev-rules-fedora-%FEDORA_VERSION%.repo

  # These RPMs will be installed from your enabled repositories.
  install:
    - android-tools
    - android-udev-rules

    - libvirt
    - qemu
    - qemu-user-static
    - qemu-user-binfmt
    - virt-manager

  # These RPMs will be removed from the system image.
  remove:
    - distrobox
